// Code generated by "stringer -type=LInsertOp,LOrderOp,FlushOP -linecomment=true -output=stringer.go"; DO NOT EDIT.

package redis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BEFORE-0]
	_ = x[AFTER-1]
}

const _LInsertOp_name = "BEFOREAFTER"

var _LInsertOp_index = [...]uint8{0, 6, 11}

func (i LInsertOp) String() string {
	if i < 0 || i >= LInsertOp(len(_LInsertOp_index)-1) {
		return "LInsertOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LInsertOp_name[_LInsertOp_index[i]:_LInsertOp_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASC-2]
	_ = x[DESC-3]
}

const _LOrderOp_name = "ASCDESC"

var _LOrderOp_index = [...]uint8{0, 3, 7}

func (i LOrderOp) String() string {
	i -= 2
	if i < 0 || i >= LOrderOp(len(_LOrderOp_index)-1) {
		return "LOrderOp(" + strconv.FormatInt(int64(i+2), 10) + ")"
	}
	return _LOrderOp_name[_LOrderOp_index[i]:_LOrderOp_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASYNC-4]
	_ = x[SYNC-5]
}

const _FlushOP_name = "ASYNCSYNC"

var _FlushOP_index = [...]uint8{0, 5, 9}

func (i FlushOP) String() string {
	i -= 4
	if i < 0 || i >= FlushOP(len(_FlushOP_index)-1) {
		return "FlushOP(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _FlushOP_name[_FlushOP_index[i]:_FlushOP_index[i+1]]
}
